export function sdkTemplate(name: string): string {
    return `import { createTSDK } from '../core/createTSDK'
import type { IMethodDefinition, ITSDKInstance, ITransport } from '../types/ITSDK'
import * as methods from './methods'

export const ${name}Plugin = { methods } satisfies { methods: Record<string, IMethodDefinition> }

export function create${capitalize(name)}SDK<TResources extends readonly string[]>(options: {
    transport: ITransport
    baseURL: string
    resources: TResources
}): ITSDKInstance<typeof ${name}Plugin.methods, TResources> {
    return createTSDK({ ...options, plugin: ${name}Plugin })
}
`
}

export function methodTemplate(name: string): string {
    return `import type { IMethodDefinition } from '../../types/ITSDK'

export const ${name}: IMethodDefinition = {
    resolve: (resource, payload) => ({
        url: \`/\${resource}/${name}\`,
        method: 'POST',
        body: payload,
    }),
}
`
}

export function resourceTemplate(name: string): string {
    return `// Generated by t-sdk CLI — complete the fields below
export interface I${capitalize(name)} {
    id: number
    created_at: string
    updated_at: string
}
`
}

function capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1)
}
